language: node_js
env:
  - NODE_PATH=$(which node)
install:
  - yarn install
  - cd API
  - yarn install
  - cd ..
services:
  - mongodb
node_js:
  - "9"
before_script:
  - cp local.travis.json API/config/local.json
script:
  - yarn lint
  - yarn test
